"""create motorcycles and maintenance_records tables

Revision ID: 65c1f6f39a06
Revises: 
Create Date: 2026-04-20 22:10:09.806939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c1f6f39a06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('front_sprocket', sa.Integer(), nullable=False),
    sa.Column('rear_sprocket', sa.Integer(), nullable=False),
    sa.Column('chain_links', sa.Integer(), nullable=False),
    sa.Column('tire_circumference_mm', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('chain_links > 0', name='ck_motorcycles_chain_links_positive'),
    sa.CheckConstraint('front_sprocket > 0', name='ck_motorcycles_front_sprocket_positive'),
    sa.CheckConstraint('rear_sprocket > 0', name='ck_motorcycles_rear_sprocket_positive'),
    sa.CheckConstraint('tire_circumference_mm > 0', name='ck_motorcycles_tire_circumference_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorcycle_id', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.Date(), nullable=False),
    sa.Column('odometer_km', sa.Integer(), nullable=False),
    sa.Column('lubricant', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('odometer_km >= 0', name='ck_maintenance_records_odometer_nonneg'),
    sa.ForeignKeyConstraint(['motorcycle_id'], ['motorcycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index('idx_maintenance_records_motorcycle_performed', ['motorcycle_id', 'performed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index('idx_maintenance_records_motorcycle_performed')

    op.drop_table('maintenance_records')
    op.drop_table('motorcycles')
    # ### end Alembic commands ###
